# Generated by Django 5.2.4 on 2025-07-08 22:26

import core.models
import stdimage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criados', models.DateField(auto_now_add=True, verbose_name='Data de Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('imagem', stdimage.models.StdImageField(force_min_size=False, upload_to=core.models.get_file_path, variations={'thumb': {'crop': True, 'height': 600, 'width': 800}}, verbose_name='Imagem')),
                ('prato', models.CharField(max_length=80, verbose_name='Nome do Prato')),
                ('descricao', models.CharField(max_length=200, verbose_name='Descrição do Prato')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor do produto')),
            ],
            options={
                'verbose_name': 'Menu',
                'verbose_name_plural': 'Menus',
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criados', models.DateField(auto_now_add=True, verbose_name='Data de Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('nome', models.CharField(max_length=80, verbose_name='Nome')),
                ('telefone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('pessoas', models.IntegerField(verbose_name='Quantidade de Pessoas')),
                ('data', models.DateField(verbose_name='Data da reserva')),
                ('horario', models.TimeField(verbose_name='Hora da reserva')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
            },
        ),
        migrations.CreateModel(
            name='Servicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criados', models.DateField(auto_now_add=True, verbose_name='Data de Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('icone', models.CharField(choices=[('ti-face-smile', 'Smile'), ('ti-thought', 'Nuvem'), ('ti-truck', 'Caminhão')], max_length=15, verbose_name='Icone')),
                ('servico', models.CharField(max_length=80, verbose_name='Serviço')),
                ('descricao', models.CharField(max_length=200, verbose_name='Descrição Serviço')),
            ],
            options={
                'verbose_name': 'Serviço',
                'verbose_name_plural': 'Serviços',
            },
        ),
        migrations.CreateModel(
            name='Sub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criados', models.DateField(auto_now_add=True, verbose_name='Data de Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('email', models.EmailField(max_length=254, verbose_name='Email do sub')),
            ],
            options={
                'verbose_name': 'Sub',
                'verbose_name_plural': 'Subs',
            },
        ),
    ]
