# Generated by Django 5.2.4 on 2025-07-10 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reserva',
            old_name='data',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='reserva',
            old_name='horario',
            new_name='time',
        ),
    ]
